services:
  db:
    image: "postgres"
    container_name: "postgress_db"
    environment:
      - "POSTGRES_USER": "flet_app"
      - "POSTGRES_PASSWORD" : "kupcake"
      - "POSTGRES_DB" : "project"
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data